### ISSUE TITLE
MCPのresources機能を実装する

### ISSUE THREAD

**Issue by kk6** [kk6/minerva#2]
## 概要

MCP (Model Context Protocol)のresources機能を実装し、Obsidian保管庫の設定や各種テンプレートを管理できるようにします。

## 目的

- 保管庫のパス、デフォルトの保存場所などの設定を集中管理する
- ノートテンプレートをYAML形式で定義し、柔軟に利用できるようにする
- Claude Desktopへの指示内容を構造化して管理する

### 1. 基本構造
```
minerva/
  ├── resources/
  │   ├── obsidian_config.yaml (保管庫設定)
  │   ├── note_templates.yaml (ノートテンプレート)
  │   └── claude_instructions.yaml (Claude指示用プロンプト)
```

### 2. 設定ファイル例

**obsidian_config.yaml**
```yaml
name: obsidian_config
content:
  vault_path: "/Users/username/Documents/Obsidian/MainVault"
  templates_folder: "Templates"
  default_note_location: "Inbox"
  date_format: "YYYY-MM-DD"
```

**note_templates.yaml**
```yaml
name: note_templates
content:
  meeting_notes:
    title: "会議ノート: {{title}}"
    content: |
      # {{title}}
      
      日時: {{date}}
      参加者: {{participants}}
      
      ## アジェンダ
      ...
```

### 3. リソース管理クラスの実装

- リソースファイルの読み込み機能
- テンプレート処理（変数の置換など）
- Obsidian保管庫との連携

## 技術的詳細

- PyYAMLを使用してYAMLファイルを読み込む
- テンプレートエンジン（Jinja2など）を使用して変数置換を行う
- 設定の検証機能を追加する

## 関連機能

- MCPのprompts機能との連携
- CLIからの設定変更・管理コマンドの提供

## タスク

- [ ] リソースディレクトリ構造の作成
- [ ] 基本設定ファイルの実装
- [ ] リソース管理クラスの実装
- [ ] Obsidian保管庫アクセスクラスとの統合
- [ ] テスト作成
- [ ] ドキュメント更新
