### ISSUE TITLE
[FEATURE] スマートエイリアス機能の実装

### ISSUE THREAD

**Issue by kk6** [kk6/minerva#32]
## 🚀 提案する機能
ファイル名とは別に、複数のエイリアス（別名）でノートを参照できる機能を実装する。

## 解決する課題
- 「meeting_20250523.md」のような機械的なファイル名を「先週の定例」のような自然な名前でも参照したい
- 同じノートを異なる文脈で呼びたい（「Python入門」「プログラミング基礎」など）
- ファイル名を変更せずに、より検索しやすい別名を付けたい

## 想定している解決策
```python
def add_alias(
    filename: str,
    aliases: list[str],
    default_path: str = DEFAULT_NOTE_DIR
) -> Path:
    """ノートにエイリアスを追加（フロントマターのaliasesフィールド）"""

def search_by_alias(
    alias: str,
    exact_match: bool = False
) -> list[NoteInfo]:
    """エイリアスでノートを検索"""
```

### 使用例
```
「meeting_20250523.md」に「先週の定例」「5月の振り返り」というエイリアスを追加してください
```

### フロントマターの例
```yaml
---
aliases:
  - 先週の定例
  - 5月の振り返り
  - プロジェクトX定例会
created: 2025-05-23T10:00:00
---
```

## 代替案の検討
- ファイル名自体を変更 → リンクが壊れる可能性
- タグで管理 → 正確な一意の参照ができない

## 追加情報
- Obsidian標準のaliasesフィールドを使用するため互換性が高い
- エイリアスの重複チェック機能も必要
- 既存のsearch_notes関数を拡張してエイリアス検索にも対応
